### ISSUE TITLE
Cancel subscription response inconsistency 

### ISSUE THREAD

**Issue by khorvat** [braintree/braintree_dotnet#21] opened 2015-11-24 12:57 UTC
Hi,

 I'm just testing cancel subscription and response is inconsistent. I'm expecting to check _IsSuccess()_ to see if error has occured as this is the approach for all other methods Transaction and subscription but I get the following error which I consider as inconsistent response behavior:

```
Result Message:	Braintree.Exceptions.NotFoundException : Exception of type 'Braintree.Exceptions.NotFoundException' was thrown.
Result StackTrace:	
at Braintree.BraintreeService.ThrowExceptionIfErrorStatusCode(HttpStatusCode httpStatusCode, String message)
   at Braintree.BraintreeService.GetXmlResponse(String URL, String method, Request requestBody)
   at Braintree.BraintreeService.Put(String URL, Request requestBody)
   at Braintree.BraintreeService.Put(String URL)
   at Braintree.SubscriptionGateway.Cancel(String id)
   at 
```

Do you plan to fix this and make it consistent or there are some other reasons to throw exception here ?

Regards

**Comment by kexline4710** [comment] 2015-11-30 16:45
Hi @khorvat! That does seem odd; however, I was unable to recreate this error when trying to cancel a subscription. Could you provide the version of this library you are using and additional code snippets of how you cancel the subscription and check the result object for its success?

**Comment by kexline4710** [comment] 2016-01-04 16:00
Since we cannot recreate this problem, I'm going to close this issue. Feel free to reopen with steps to reproduce this error if it comes up again!

**Closed by kexline4710** 2016-01-04 16:00 UTC
