### ISSUE TITLE
Braintree 2.51.0 does not support .NetPlatform v5.4

### ISSUE THREAD

**Issue by mkarlsson** [braintree/braintree_dotnet#20] opened 2015-11-19 17:47 UTC
Reproduce by creating a new ASP.NET5 project. 
Add Braintree nuget package. 
Reference won't be added for .NET platform 5.4 but only for 4.5.1(.Net 4.6).

**Comment by raymondberg** [comment] 2015-12-15 21:34
Hi, @mkarlsson. We've been able to produce similar results and will be working to resolve this issue. We'll let you know if we have any status/questions for you.

**Comment by dwdickens** [comment] 2016-03-12 04:47
+1 to resolve this. .Net Core is fantastic and the lack of compatability is making me look at Stripe's rest interface instead. It doesn't look like there's much to convert to move Braintree dotnet across - this is a good starting point: https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b

**Comment by otabekgb** [comment] 2016-07-06 01:11
Please, add .Net Core support.

**Comment by thoughtentity** [comment] 2016-08-26 23:29
Adding another vote for this, especially now that .NET Core 1.0 [RTM'd in late June 2016](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/). This is actually a blocker for us deploying on Windows Nano Server since **ONLY** the .NET Core CLR is supported on that platform. Targeting the .NET Braintree library on a [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) would also future proof the library and allow it to run on an expanded set of platforms including OSX, Linux and mobile platforms such as iOS and Android through Xamarin.

**Comment by raymondberg** [comment] 2016-09-07 16:47
@mkarlsson @thoughtentity @otabekgb @dwdickens @gregbty @senwen @abhurtun

We've released 3.0.0 which deprecates support for older platforms and targets support for .NET Core. We'd love feedback on it and for some early integrations to test our solution. 

I'm going to close this issue as 3.0.0 addresses this support, but please open other issues or PRs if you discover any improvements we can make. We really appreciate your voices on this!

**Comment by senwen** [comment] 2016-09-07 17:36
@raymondberg 
I just tried pulling latest from nuget and doing a restore and got this error:

_Package Braintree 3.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Braintree 3.0.0 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0._

Anyone else running this issue?

**Comment by raymondberg** [comment] 2016-09-07 17:43
Thanks for reporting it, Senwen!

**Comment by thoughtentity** [comment] 2016-09-07 18:20
Quick thing I noticed in the `project.json` file is that the Braintree library is targeting `netcoreapp10` the actual TFM should be `netcoreapp1.0` which is likely the cause for the error.

Though the bigger issue is that the Braintree library is using the `netcoreapp` TFM in the first place which is meant for full applications not libraries. Libraries like Braintree are supposed to target a .Net Standard version based on the required BCL APIs it needs. The TFM for .Net Standard is`netstandard` so a TFM targeting .Net Standard 1.2 would like this `netstandard1.2`. The .Net Standard platform has a much smaller dependency chain then .Net Core App platform.

**Comment by senwen** [comment] 2016-09-07 18:38
Also, for dotnet core, the dependency  `Microsoft.AspNet.WebUtilities` should be `Microsoft.AspNetCore.WebUtilities 1.0.0` .

**Comment by raymondberg** [comment] 2016-09-08 17:13
Thanks again, @thoughtentity and @senwen, for your follow-up. We were able to release [3.0.1](https://github.com/braintree/braintree_dotnet/releases/tag/3.0.1) using a different publishing mechanism to ensure both versions of the dll are exposed. Our tests show a fully compatible nuget package on our side; please let us know if you see the same!

**Comment by senwen** [comment] 2016-09-08 18:54
@raymondberg,
Passed tests for our use cases on Windows, Mac and Linux.
Thanks!

**Closed** 2016-09-12 14:41 UTC
